name: wakelock_web
description: Web platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.8.0
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock_web

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  js: ^0.6.3

  wakelock_platform_interface: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

  wakelock:
    path: ../wakelock

flutter:
  plugin:
    platforms:
      web:
        pluginClass: WakelockWeb
        fileName: wakelock_web.dart

  assets:
    - assets/no_sleep.js
