name: wakelock
description: >-2
  Plugin that allows you to keep the device screen awake, i.e. prevent the screen from sleeping on
  Android, iOS, macOS, Windows, and web.
version: 0.5.4
homepage: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.2.0

  wakelock_macos: ^0.1.0+1
  wakelock_platform_interface: ^0.2.1+1
  wakelock_web: ^0.2.0+1
  wakelock_windows: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  pigeon: ^1.0.2 # flutter pub run pigeon --input "pigeons/messages.dart" --dart_out "../wakelock_platform_interface/lib/messages.dart"

flutter:
  plugin:
    platforms:
      android:
        package: creativemaybeno.wakelock
        pluginClass: WakelockPlugin
      ios:
        pluginClass: WakelockPlugin
      macos:
        default_package: wakelock_macos
      windows:
        default_package: wakelock_windows
      web:
        default_package: wakelock_web
