name: wakelock_linux
description: >-
  Linux platform implementation of the wakelock_platform_interface for the
  wakelock plugin.
version: 0.1.0
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock_linux

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  dbus: ^0.7.8
  flutter:
    sdk: flutter
  meta: ^1.8.0
  package_info_plus: ^3.0.2
  wakelock_platform_interface: ^0.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

flutter:
  plugin:
    platforms:
      linux:
        dartPluginClass: WakelockLinux
