name: wakelock_macos
description: >-2
  macOS platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.8.0
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock_macos

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  wakelock_platform_interface: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WakelockMacosPlugin
        fileName: wakelock_macos.dart
